package temap

type WorldHeader struct {
	Name                    string
	Seed                    string
	GenVersion              uint64
	GUID                    [16]byte
	WorldID                 uint32
	LeftWorld               uint32
	RightWorld              uint32
	TopWorld                uint32
	BottomWorld             uint32
	MaxTilesY               uint32
	MaxTilesX               uint32
	GameMode                uint32
	DrunkWorld              bool
	CreationTime            uint64
	MoonType                uint8
	TreeX                   [3]uint32
	TreeStyle               [4]uint32
	CaveBackX               [3]uint32
	CaveBackStyle           [4]uint32
	Styles                  [8]uint8
	IceBackStyle            uint32
	JungleBackStyle         uint32
	HellBackStyle           uint32
	SpawnTileX              uint32
	SpawnTileY              uint32
	WorldSurface            float64
	RockLayer               float64
	DungeonX                uint32
	DungeonY                uint32
	Crimson                 bool
	DownedBoss1             bool
	DownedBoss2             bool
	DownedBoss3             bool
	DownedQueenBee          bool
	DownedMechBoss1         bool
	DownedMechBoss2         bool
	DownedMechBoss3         bool
	DownedMechBossAny       bool
	DownedPlantBoss         bool
	DownedGolemBoss         bool
	DownedSlimeKing         bool
	SavedGoblin             bool
	SavedWizard             bool
	SavedMech               bool
	DownedGoblins           bool
	DownedClown             bool
	DownedFrost             bool
	DownedPirates           bool
	ShadowOrbSmashed        bool
	SpawnMeteor             bool
	ShadowOrbCount          uint8
	AltarCount              uint32
	HardMode                bool
	InvasionDelay           uint32
	InvasionSize            uint32
	InvasionType            uint32
	InvasionX               float64
	SlimeRainTime           float64
	SundialCooldown         uint8
	SavedOreTiersCobalt     uint32
	SavedOreTiersMythril    uint32
	SavedOreTiersAdamantite uint32
	CloudBGActive           uint32
	NumClouds               uint16
	WindSpeedTarget         float32
	SavedAngler             bool
	AnglerQuest             uint32
	SavedStylist            bool
	SavedTaxCollector       bool
	SavedGolfer             bool
	InvasionSizeStart       uint32
	FastForwardTime         bool
	DownedFishron           bool
	DownedMartians          bool
	DownedAncientCultist    bool
	DownedMoonlord          bool
	DownedHalloweenKing     bool
	DownedHalloweenTree     bool
	DownedChristmasIceQueen bool
	DownedChristmasSantank  bool
	DownedChristmasTree     bool
	DownedTowerSolar        bool
	DownedTowerVortex       bool
	DownedTowerNebula       bool
	DownedTowerStardust     bool
	TowerActiveSolar        bool
	TowerActiveVortex       bool
	TowerActiveNebula       bool
	TowerActiveStardust     bool
	LunarApocalypseIsUp     bool
	SavedBartender          bool
	CombatBookWasUsed       bool
	ForceHalloweenForToday  bool
	ForceXMasForToday       bool
	SavedOreTiersCopper     uint32
	SavedOreTiersIron       uint32
	SavedOreTiersSilver     uint32
	SavedOreTiersGold       uint32
	BoughtCat               bool
	BoughtDog               bool
	BoughtBunny             bool
	DownedEmpressOfLight    bool
	DownedQueenSlime        bool
}
